### ISSUE TITLE
Backend Error - Config validation error: "MONGODB_URI" is required

### ISSUE THREAD

**Issue by ghost** [sldiaz04us/kanban-project-management#1]
Hi @sldiaz04us , I'm Tamilvanan
Actually I'm looking for some free kanban projects for practicing docker deployments. While doing so. I faced below error. Please help with that. Thanks in advance.

![image](https://user-images.githubusercontent.com/77013534/208874139-6e3fd442-e58f-4ac2-aa00-1f33df432ea9.png)

Thanks in advance.
Tamilvanan G

**Comment by sldiaz04us** [comment]
Hi @tamilvanang2000 

You must follow the back-end instructions in the README.md file.

![image](https://user-images.githubusercontent.com/61401062/209689728-e5e12bfb-067c-46f1-b2db-2a0f3844d8ee.png)
